#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/aditya/nrn-7.1"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/aditya/nrn-7.1/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/aditya/aditya_OB_model/cells/PG_nrn/x86_64/.libs/libnrnmech.so" "$@"
